// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX9aS0LVS_8ATZgcuZpFkwYLhHyzxXgHI',
    appId: '1:639309456805:web:a3c56a168a756cc1f1f44c',
    messagingSenderId: '639309456805',
    projectId: 'habit-tracker-c7875',
    authDomain: 'habit-tracker-c7875.firebaseapp.com',
    storageBucket: 'habit-tracker-c7875.firebasestorage.app',
    measurementId: 'G-99J3X7HLMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1r-LszwiX_EAle98YRARKv9M-8PO_dPE',
    appId: '1:639309456805:android:3770c007f6bbc6d2f1f44c',
    messagingSenderId: '639309456805',
    projectId: 'habit-tracker-c7875',
    storageBucket: 'habit-tracker-c7875.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF4au_XudvgtmZ3s0rTwaTPViuyJCLG3I',
    appId: '1:639309456805:ios:0404781c6726cd86f1f44c',
    messagingSenderId: '639309456805',
    projectId: 'habit-tracker-c7875',
    storageBucket: 'habit-tracker-c7875.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF4au_XudvgtmZ3s0rTwaTPViuyJCLG3I',
    appId: '1:639309456805:ios:0404781c6726cd86f1f44c',
    messagingSenderId: '639309456805',
    projectId: 'habit-tracker-c7875',
    storageBucket: 'habit-tracker-c7875.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX9aS0LVS_8ATZgcuZpFkwYLhHyzxXgHI',
    appId: '1:639309456805:web:33a93be19efbfaa5f1f44c',
    messagingSenderId: '639309456805',
    projectId: 'habit-tracker-c7875',
    authDomain: 'habit-tracker-c7875.firebaseapp.com',
    storageBucket: 'habit-tracker-c7875.firebasestorage.app',
    measurementId: 'G-BZ0P8WMRTP',
  );
}
